### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by ylhua** [guochengqian/Magic123#1]
Thanks for your great job and fantastic idea! By the way, may I ask when will the code be released?

**Comment by guochengqian** [comment]
in two to four weeks

**Comment by eran-sefirot** [comment]
+1

**Comment by exgbit** [comment]
can't wait

**Comment by DiamondGlassDrill** [comment]
Looking forward to the release :)

**Comment by firefhy** [comment]
can't wait +1

**Comment by Avey777** [comment]
+1

**Comment by xiaoquan-serien** [comment]
kit me after release

**Comment by xiaoquan-serien** [comment]
kit me after release

**Comment by anandvarrier** [comment]
+1

**Comment by yuhaokung** [comment]
这个项目真的太棒了，顺便问一下代码什么时候发布？

**Comment by guochengqian** [comment]
hi all, I am dedicated my working hours to this release plan today.

**Comment by dubeno** [comment]
cant't wait thanks

**Comment by guochengqian** [comment]
Done. 
Just test with a ironman photo from internet. Looks good. 
Take a try and let me know what I can help.
I will try to regularly check issues once per month.

Thank you all for the interest!

**Comment by yuhaokung** [comment]
Has anyone run it yet?Do path and data files need to be created based on their own data？
