### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/tets/256_tets.npz'

### ISSUE THREAD

**Issue by zyhrainbow** [guochengqian/Magic123#10]
FileNotFoundError: [Errno 2] No such file or directory: 'data/tets/256_tets.npz'
how to get the file？Thanks~

**Comment by yufeng9819** [comment]
Hi, I also meet the same problem. Can I ask how to solve this problem? (I find you close this issue and you may found the solution)

Thanks.

**Comment by zyhrainbow** [comment]
You may find the solution that in the GitHub repo of stabledreamfusion, there is a file of tets, you can get the answer in the generate.py 

https://github.com/ashawkey/stable-dreamfusion/tree/main/tets 

发件人: "yufeng9819" ***@***.***> 
收件人: "guochengqian/Magic123" ***@***.***> 
抄送: "ZYuhong" ***@***.***>, "State change" ***@***.***> 
已发送邮件: 星期五, 8 月 4, 2023 07:28:53 PM 
主题: Re: [guochengqian/Magic123] FileNotFoundError: [Errno 2] No such file or directory: 'data/tets/256_tets.npz' (Issue #10) 

Hi, I also meet the same problem. Can I ask how to solve this problem? (I find you close this issue and you may found the solution) 

Thanks.
