### ISSUE TITLE
one Running error with bash scripts/magic123/run_both_priors.sh 0 default dmtet data/realfusion15/metal_dragon_statue rgba.png 1 1 

### ISSUE THREAD

**Issue by xzr52** [guochengqian/Magic123#11]
(nerfart) root@interactive43861:/opt/data/private/image_to_3d/Magic123-main# bash scripts/magic123/run_both_priors.sh 0 default dmtet /opt/data/private/image_to_3d/Magic123-main/data/bird_sparrow rgba.png 1 1 --lambda
_guidance 1 40
scripts/magic123/run_both_priors.sh: line 13: module: command not found
scripts/magic123/run_both_priors.sh: line 18: venv_magic123/bin/activate: No such file or directory
/root/anaconda3/envs/nerfart/bin/python
Thu Aug  3 18:22:14 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.91.03    Driver Version: 460.91.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 3090    Off  | 00000000:1B:00.0 Off |                  N/A |
| 30%   32C    P8    28W / 350W |      0MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 3090    Off  | 00000000:3D:00.0 Off |                  N/A |
| 30%   28C    P8    16W / 350W |      0MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0
interactive43861
number of gpus: 2
reconstruct bird_sparrow under dataset data from folder /opt/data/private/image_to_3d/Magic123-main/data/bird_sparrow ...
[23/08/03 18:30:29 __main__]: NeRFNetwork(
  (encoder): GridEncoder: input_dim=3 num_levels=16 level_dim=2 resolution=16 -> 2048 per_level_scale=1.3819 params=(6098120, 2) gridtype=hash align_corners=False interpolation=smoothstep
  (sigma_net): MLP(
    (net): ModuleList(
      (0): Linear(in_features=32, out_features=64, bias=True)
      (1): Linear(in_features=64, out_features=64, bias=True)
      (2): Linear(in_features=64, out_features=4, bias=True)
    )
  )
)
WARNING [23/08/03 18:30:30 xformers]: WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 1.13.1+cu117)
    Python  3.8.16 (you have 3.8.16)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
[23/08/03 18:30:32 guidance.sd_utils]: [INFO] loading stable diffusion...
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /root/anaconda3/envs/nerfart/lib/python3.8/site-packages/urllib3/connectionpool.py:670 in        │
│ urlopen                                                                                          │
│                                                                                                  │
│    667 │   │   │   │   self._prepare_proxy(conn)                                                 │
│    668 │   │   │                                                                                 │
│    669 │   │   │   # Make the request on the httplib connection object.                          │
│ ❱  670 │   │   │   httplib_response = self._make_request(                                        │
│    671 │   │   │   │   conn,                                                                     │
│    672 │   │   │   │   method,                                                                   │
│    673 │   │   │   │   url,                                                                      │
│                                                                                                  │
│ /root/anaconda3/envs/nerfart/lib/python3.8/site-packages/urllib3/connectionpool.py:381 in        │
│ _make_request                                                                                    │
│                                                                                                  │
│    378 │   │                                                                                     │
│    379 │   │   # Trigger any extra validation we need to do.                                     │
│    380 │   │   try:                                                                              │
│ ❱  381 │   │   │   self._validate_conn(conn)                                                     │
│    382 │   │   except (SocketTimeout, BaseSSLError) as e:                                        │
│    383 │   │   │   # Py2 raises this as a BaseSSLError, Py3 raises it as socket timeout.         │
│    384 │   │   │   self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)               │
│                                                                                                  │
│ /root/anaconda3/envs/nerfart/lib/python3.8/site-packages/urllib3/connectionpool.py:978 in        │
│ _validate_conn                                                                                   │
│                                                                                                  │
│    975 │   │                                                                                     │
│    976 │   │   # Force connect early to allow us to validate the connection.                     │
│    977 │   │   if not getattr(conn, "sock", None):  # AppEngine might not have  `.sock`          │
│ ❱  978 │   │   │   conn.connect()                                                                │
│    979 │   │                                                                                     │
│    980 │   │   if not conn.is_verified:                                                          │
│    981 │   │   │   warnings.warn(                                                                │
│                                                                                                  │
│ /root/anaconda3/envs/nerfart/lib/python3.8/site-packages/urllib3/connection.py:362 in connect    │
│                                                                                                  │
│   359 │   │   ):                                                                                 │
│   360 │   │   │   context.load_default_certs()                                                   │
│   361 │   │                                                                                      │
│ ❱ 362 │   │   self.sock = ssl_wrap_socket(                                                       │
│   363 │   │   │   sock=conn,                                                                     │
│   364 │   │   │   keyfile=self.key_file,                                                         │
│   365 │   │   │   certfile=self.cert_file,                                                       │
│                                                                                                  │
│ /root/anaconda3/envs/nerfart/lib/python3.8/site-packages/urllib3/util/ssl_.py:386 in             │
│ ssl_wrap_socket                                                                                  │
│                                                                                                  │
│   383 │   │   server_hostname is not None and not is_ipaddress(server_hostname)                  │
│   384 │   ) or IS_SECURETRANSPORT:                                                               │
│   385 │   │   if HAS_SNI and server_hostname is not None:                                        │
│ ❱ 386 │   │   │   return context.wrap_socket(sock, server_hostname=server_hostname)              │
│   387 │   │                                                                                      │
│   388 │   │   warnings.warn(                                                                     │
│   389 │   │   │   "An HTTPS request has been made, but the SNI (Server Name "                    │
│                                                                                                  │
│ /root/anaconda3/envs/nerfart/lib/python3.8/ssl.py:500 in wrap_socket                             │
│                                                                                                  │
│    497 │   │   │   │   │   server_hostname=None, session=None):                                  │
│    498 │   │   # SSLSocket class handles server_hostname encoding before it calls                │
│    499 │   │   # ctx._wrap_socket()                                                              │
│ ❱  500 │   │   return self.sslsocket_class._create(                                              │
│    501 │   │   │   sock=sock,                                                                    │
│    502 │   │   │   server_side=server_side,                                                      │
│    503 │   │   │   do_handshake_on_connect=do_handshake_on_connect,                              │
│                                                                                                  │
│ /root/anaconda3/envs/nerfart/lib/python3.8/ssl.py:1040 in _create                                │
│                                                                                                  │
│   1037 │   │   │   │   │   if timeout == 0.0:                                                    │
│   1038 │   │   │   │   │   │   # non-blocking                                                    │
│   1039 │   │   │   │   │   │   raise ValueError("do_handshake_on_connect should not be specifie  │
│ ❱ 1040 │   │   │   │   │   self.do_handshake()                                                   │
│   1041 │   │   │   except (OSError, ValueError):                                                 │
│   1042 │   │   │   │   self.close()                                                              │
│   1043 │   │   │   │   raise                                                                     │
│                                                                                                  │
│ /root/anaconda3/envs/nerfart/lib/python3.8/ssl.py:1309 in do_handshake                           │
│                                                                                                  │
│   1306 │   │   try:                                                                              │
│   1307 │   │   │   if timeout == 0.0 and block:                                                  │
│   1308 │   │   │   │   self.settimeout(None)                                                     │
│ ❱ 1309 │   │   │   self._sslobj.do_handshake()                                                   │
│   1310 │   │   finally:                                                                          │
│   1311 │   │   │   self.settimeout(timeout)                                                      │
│   1312                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /root/anaconda3/envs/nerfart/lib/python3.8/site-packages/requests/adapters.py:486 in send        │
│                                                                                                  │
│   483 │   │   │   timeout = TimeoutSauce(connect=timeout, read=timeout)                          │
│   484 │   │                                                                                      │
│   485 │   │   try:                                                                               │
│ ❱ 486 │   │   │   resp = conn.urlopen(                                                           │
│   487 │   │   │   │   method=request.method,                                                     │
│   488 │   │   │   │   url=url,                                                                   │
│   489 │   │   │   │   body=request.body,                                                         │
│                                                                                                  │
│ /root/anaconda3/envs/nerfart/lib/python3.8/site-packages/urllib3/connectionpool.py:726 in        │
│ urlopen                                                                                          │
│                                                                                                  │
│    723 │   │   │   elif isinstance(e, (SocketError, HTTPException)):                             │
│    724 │   │   │   │   e = ProtocolError("Connection aborted.", e)                               │
│    725 │   │   │                                                                                 │
│ ❱  726 │   │   │   retries = retries.increment(                                                  │
│    727 │   │   │   │   method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]           │
│    728 │   │   │   )                                                                             │
│    729 │   │   │   retries.sleep()                                                               │
│                                                                                                  │
│ /root/anaconda3/envs/nerfart/lib/python3.8/site-packages/urllib3/util/retry.py:410 in increment  │
│                                                                                                  │
│   407 │   │   elif error and self._is_read_error(error):                                         │
│   408 │   │   │   # Read retry?                                                                  │
│   409 │   │   │   if read is False or not self._is_method_retryable(method):                     │
│ ❱ 410 │   │   │   │   raise six.reraise(type(error), error, _stacktrace)                         │
│   411 │   │   │   elif read is not None:                                                         │
│   412 │   │   │   │   read -= 1                                                                  │
│   413                                                                                            │
│                                                                                                  │
│ /root/anaconda3/envs/nerfart/lib/python3.8/site-packages/urllib3/packages/six.py:734 in reraise  │
│                                                                                                  │
│    731 │   │   │   if value is None:                                                             │
│    732 │   │   │   │   value = tp()                                                              │
│    733 │   │   │   if value.__traceback__ is not tb:                                             │
│ ❱  734 │   │   │   │   raise value.with_traceback(tb)                                            │
│    735 │   │   │   raise value                                                                   │
│    736 │   │   finally:                                                                          │
│    737 │   │   │   value = None                                                                  │
│                                                                                                  │
│ /root/anaconda3/envs/nerfart/lib/python3.8/site-packages/urllib3/connectionpool.py:670 in        │
│ urlopen                                                                                          │
│                                                                                                  │
│    667 │   │   │   │   self._prepare_proxy(conn)                                                 │
│    668 │   │   │                                                                                 │
│    669 │   │   │   # Make the request on the httplib connection object.                          │
│ ❱  670 │   │   │   httplib_response = self._make_request(                                        │
│    671 │   │   │   │   conn,                                                                     │
│    672 │   │   │   │   method,                                                                   │
│    673 │   │   │   │   url,                                                                      │
│                                                                                                  │
│ /root/anaconda3/envs/nerfart/lib/python3.8/site-packages/urllib3/connectionpool.py:381 in        │
│ _make_request                                                                                    │
│                                                                                                  │
│    378 │   │                                                                                     │
│    379 │   │   # Trigger any extra validation we need to do.                                     │
│    380 │   │   try:                                                                              │
│ ❱  381 │   │   │   self._validate_conn(conn)                                                     │
│    382 │   │   except (SocketTimeout, BaseSSLError) as e:                                        │
│    383 │   │   │   # Py2 raises this as a BaseSSLError, Py3 raises it as socket timeout.         │
│    384 │   │   │   self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)               │
│                                                                                                  │
│ /root/anaconda3/envs/nerfart/lib/python3.8/site-packages/urllib3/connectionpool.py:978 in        │
│ _validate_conn                                                                                   │
│                                                                                                  │
│    975 │   │                                                                                     │
│    976 │   │   # Force connect early to allow us to validate the connection.                     │
│    977 │   │   if not getattr(conn, "sock", None):  # AppEngine might not have  `.sock`          │
│ ❱  978 │   │   │   conn.connect()                                                                │
│    979 │   │                                                                                     │
│    980 │   │   if not conn.is_verified:                                                          │
│    981 │   │   │   warnings.warn(                                                                │
│                                                                                                  │
│ /root/anaconda3/envs/nerfart/lib/python3.8/site-packages/urllib3/connection.py:362 in connect    │
│                                                                                                  │
│   359 │   │   ):                                                                                 │
│   360 │   │   │   context.load_default_certs()                                                   │
│   361 │   │                                                                                      │
│ ❱ 362 │   │   self.sock = ssl_wrap_socket(                                                       │
│   363 │   │   │   sock=conn,                                                                     │
│   364 │   │   │   keyfile=self.key_file,                                                         │
│   365 │   │   │   certfile=self.cert_file,                                                       │
│                                                                                                  │
│ /root/anaconda3/envs/nerfart/lib/python3.8/site-packages/urllib3/util/ssl_.py:386 in             │
│ ssl_wrap_socket                                                                                  │
│                                                                                                  │
│   383 │   │   server_hostname is not None and not is_ipaddress(server_hostname)                  │
│   384 │   ) or IS_SECURETRANSPORT:                                                               │
│   385 │   │   if HAS_SNI and server_hostname is not None:                                        │
│ ❱ 386 │   │   │   return context.wrap_socket(sock, server_hostname=server_hostname)              │
│   387 │   │                                                                                      │
│   388 │   │   warnings.warn(                                                                     │
│   389 │   │   │   "An HTTPS request has been made, but the SNI (Server Name "                    │
│                                                                                                  │
│ /root/anaconda3/envs/nerfart/lib/python3.8/ssl.py:500 in wrap_socket                             │
│                                                                                                  │
│    497 │   │   │   │   │   server_hostname=None, session=None):                                  │
│    498 │   │   # SSLSocket class handles server_hostname encoding before it calls                │
│    499 │   │   # ctx._wrap_socket()                                                              │
│ ❱  500 │   │   return self.sslsocket_class._create(                                              │
│    501 │   │   │   sock=sock,                                                                    │
│    502 │   │   │   server_side=server_side,                                                      │
│    503 │   │   │   do_handshake_on_connect=do_handshake_on_connect,                              │
│                                                                                                  │
│ /root/anaconda3/envs/nerfart/lib/python3.8/ssl.py:1040 in _create                                │
│                                                                                                  │
│   1037 │   │   │   │   │   if timeout == 0.0:                                                    │
│   1038 │   │   │   │   │   │   # non-blocking                                                    │
│   1039 │   │   │   │   │   │   raise ValueError("do_handshake_on_connect should not be specifie  │
│ ❱ 1040 │   │   │   │   │   self.do_handshake()                                                   │
│   1041 │   │   │   except (OSError, ValueError):                                                 │
│   1042 │   │   │   │   self.close()                                                              │
│   1043 │   │   │   │   raise                                                                     │
│                                                                                                  │
│ /root/anaconda3/envs/nerfart/lib/python3.8/ssl.py:1309 in do_handshake                           │
│                                                                                                  │
│   1306 │   │   try:                                                                              │
│   1307 │   │   │   if timeout == 0.0 and block:                                                  │
│   1308 │   │   │   │   self.settimeout(None)                                                     │
│ ❱ 1309 │   │   │   self._sslobj.do_handshake()                                                   │
│   1310 │   │   finally:                                                                          │
│   1311 │   │   │   self.settimeout(timeout)                                                      │
│   1312                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /opt/data/private/image_to_3d/Magic123-main/main.py:573 in <module>                              │
│                                                                                                  │
│   570 │   │   │   │   opt.guidance_scale) else opt.guidance_scale[-1]                            │
│   571 │   │   │   if 'SD' == guidance_type:                                                      │
│   572 │   │   │   │   from guidance.sd_utils import StableDiffusion, token_replace               │
│ ❱ 573 │   │   │   │   guidance['SD'] = StableDiffusion(device, opt.fp16, opt.vram_O, opt.sd_ve   │
│   574 │   │   │   │   │   │   │   │   │   │   │   │    learned_embeds_path=opt.learned_embeds_   │
│   575 │   │   │   │   │   │   │   │   │   │   │   │    use_clip=opt.use_clip, clip_t=opt.clip_   │
│   576 │   │   │   │   │   │   │   │   │   │   │   │    )                                         │
│                                                                                                  │
│ /opt/data/private/image_to_3d/Magic123-main/guidance/sd_utils.py:150 in __init__                 │
│                                                                                                  │
│   147 │   │   self.precision_t = torch.float16 if fp16 else torch.float32                        │
│   148 │   │                                                                                      │
│   149 │   │   # Create model                                                                     │
│ ❱ 150 │   │   pipe = StableDiffusionPipeline.from_pretrained(                                    │
│   151 │   │   │   sd_path, torch_dtype=self.precision_t, local_files_only=False)                 │
│   152 │   │                                                                                      │
│   153 │   │   if isfile('./unet_traced.pt'):                                                     │
│                                                                                                  │
│ /root/anaconda3/envs/nerfart/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py:8 │
│ 84 in from_pretrained                                                                            │
│                                                                                                  │
│    881 │   │   # 1. Download the checkpoints and configs                                         │
│    882 │   │   # use snapshot download here to get it working from from_pretrained               │
│    883 │   │   if not os.path.isdir(pretrained_model_name_or_path):                              │
│ ❱  884 │   │   │   cached_folder = cls.download(                                                 │
│    885 │   │   │   │   pretrained_model_name_or_path,                                            │
│    886 │   │   │   │   cache_dir=cache_dir,                                                      │
│    887 │   │   │   │   resume_download=resume_download,                                          │
│                                                                                                  │
│ /root/anaconda3/envs/nerfart/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py:1 │
│ 218 in download                                                                                  │
│                                                                                                  │
│   1215 │   │   │   │   resume_download=resume_download,                                          │
│   1216 │   │   │   │   use_auth_token=use_auth_token,                                            │
│   1217 │   │   │   )                                                                             │
│ ❱ 1218 │   │   │   info = model_info(                                                            │
│   1219 │   │   │   │   pretrained_model_name,                                                    │
│   1220 │   │   │   │   use_auth_token=use_auth_token,                                            │
│   1221 │   │   │   │   revision=revision,                                                        │
│                                                                                                  │
│ /root/anaconda3/envs/nerfart/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py:12 │
│ 0 in _inner_fn                                                                                   │
│                                                                                                  │
│   117 │   │   if check_use_auth_token:                                                           │
│   118 │   │   │   kwargs = smoothly_deprecate_use_auth_token(fn_name=fn.__name__, has_token=ha   │
│   119 │   │                                                                                      │
│ ❱ 120 │   │   return fn(*args, **kwargs)                                                         │
│   121 │                                                                                          │
│   122 │   return _inner_fn  # type: ignore                                                       │
│   123                                                                                            │
│                                                                                                  │
│ /root/anaconda3/envs/nerfart/lib/python3.8/site-packages/huggingface_hub/hf_api.py:1603 in       │
│ model_info                                                                                       │
│                                                                                                  │
│   1600 │   │   │   params["securityStatus"] = True                                               │
│   1601 │   │   if files_metadata:                                                                │
│   1602 │   │   │   params["blobs"] = True                                                        │
│ ❱ 1603 │   │   r = get_session().get(path, headers=headers, timeout=timeout, params=params)      │
│   1604 │   │   hf_raise_for_status(r)                                                            │
│   1605 │   │   d = r.json()                                                                      │
│   1606 │   │   return ModelInfo(**d)                                                             │
│                                                                                                  │
│ /root/anaconda3/envs/nerfart/lib/python3.8/site-packages/requests/sessions.py:600 in get         │
│                                                                                                  │
│   597 │   │   """                                                                                │
│   598 │   │                                                                                      │
│   599 │   │   kwargs.setdefault("allow_redirects", True)                                         │
│ ❱ 600 │   │   return self.request("GET", url, **kwargs)                                          │
│   601 │                                                                                          │
│   602 │   def options(self, url, **kwargs):                                                      │
│   603 │   │   r"""Sends a OPTIONS request. Returns :class:`Response` object.                     │
│                                                                                                  │
│ /root/anaconda3/envs/nerfart/lib/python3.8/site-packages/requests/sessions.py:587 in request     │
│                                                                                                  │
│   584 │   │   │   "allow_redirects": allow_redirects,                                            │
│   585 │   │   }                                                                                  │
│   586 │   │   send_kwargs.update(settings)                                                       │
│ ❱ 587 │   │   resp = self.send(prep, **send_kwargs)                                              │
│   588 │   │                                                                                      │
│   589 │   │   return resp                                                                        │
│   590                                                                                            │
│                                                                                                  │
│ /root/anaconda3/envs/nerfart/lib/python3.8/site-packages/requests/sessions.py:701 in send        │
│                                                                                                  │
│   698 │   │   start = preferred_clock()                                                          │
│   699 │   │                                                                                      │
│   700 │   │   # Send the request                                                                 │
│ ❱ 701 │   │   r = adapter.send(request, **kwargs)                                                │
│   702 │   │                                                                                      │
│   703 │   │   # Total elapsed time of the request (approximately)                                │
│   704 │   │   elapsed = preferred_clock() - start                                                │
│                                                                                                  │
│ /root/anaconda3/envs/nerfart/lib/python3.8/site-packages/requests/adapters.py:501 in send        │
│                                                                                                  │
│   498 │   │   │   )                                                                              │
│   499 │   │                                                                                      │
│   500 │   │   except (ProtocolError, OSError) as err:                                            │
│ ❱ 501 │   │   │   raise ConnectionError(err, request=request)                                    │
│   502 │   │                                                                                      │
│   503 │   │   except MaxRetryError as e:                                                         │
│   504 │   │   │   if isinstance(e.reason, ConnectTimeoutError):                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /opt/data/private/image_to_3d/Magic123-main/main.py:472 in <module>                              │
│                                                                                                  │
│   469 │                                                                                          │
│   470 │   device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')                  │
│   471 │   opt.device = device                                                                    │
│ ❱ 472 │   model = NeRFNetwork(opt).to(device)                                                    │
│   473 │                                                                                          │
│   474 │   if opt.init_ckpt != '':                                                                │
│   475 │   │   if not os.path.exists(opt.init_ckpt):                                              │
│                                                                                                  │
│ /opt/data/private/image_to_3d/Magic123-main/nerf/network_grid.py:29 in __init__                  │
│                                                                                                  │
│    26 │   │   │   │    level_dim=2                                                               │
│    27 │   │   │   │    ):                                                                        │
│    28 │   │                                                                                      │
│ ❱  29 │   │   super().__init__(opt)                                                              │
│    30 │   │                                                                                      │
│    31 │   │   self.num_layers = opt.num_layers if hasattr(opt, 'num_layers') else num_layers     │
│    32 │   │   self.hidden_dim = opt.hidden_dim if hasattr(opt, 'hidden_dim') else hidden_dim     │
│                                                                                                  │
│ /opt/data/private/image_to_3d/Magic123-main/nerf/renderer.py:668 in __init__                     │
│                                                                                                  │
│    665 │   │                                                                                     │
│    666 │   │   # load dmtet vertices                                                             │
│    667 │   │   if self.opt.dmtet:                                                                │
│ ❱  668 │   │   │   self.dmtet = DMTetGeometry(opt.tet_grid_size, opt.tet_mlp, opt).to(opt.devic  │
│    669 │   │   │   if self.opt.h <= 2048 and self.opt.w <= 2048:                                 │
│    670 │   │   │   │   self.glctx = dr.RasterizeCudaContext()                                    │
│    671 │   │   │   else:                                                                         │
│                                                                                                  │
│ /opt/data/private/image_to_3d/Magic123-main/nerf/renderer.py:311 in __init__                     │
│                                                                                                  │
│    308 │   │   self.grid_res = grid_res                                                          │
│    309 │   │   self.marching_tets = DMTet()                                                      │
│    310 │   │                                                                                     │
│ ❱  311 │   │   tets = np.load('data/tets/{}_tets.npz'.format(self.grid_res))                     │
│    312 │   │   # for 64/128, [N=36562/277410, 3], in [-0.5, 0.5]^3                               │
│    313 │   │   self.verts = torch.tensor(                                                        │
│    314 │   │   │   tets['vertices'], dtype=torch.float32, device=self.device) * 2                │
│                                                                                                  │
│ /root/anaconda3/envs/nerfart/lib/python3.8/site-packages/numpy/lib/npyio.py:407 in load          │
│                                                                                                  │
│    404 │   │   │   fid = file                                                                    │
│    405 │   │   │   own_fid = False                                                               │
│    406 │   │   else:                                                                             │
│ ❱  407 │   │   │   fid = stack.enter_context(open(os_fspath(file), "rb"))                        │
│    408 │   │   │   own_fid = True                                                                │
│    409 │   │                                                                                     │
│    410 │   │   # Code to distinguish from NumPy binary files and pickles.                        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
FileNotFoundError: [Errno 2] No such file or directory: 'data/tets/256_tets.npz
please tell me where i can find the 256_tets.npz,i will thank you very much

**Comment by guochengqian** [comment]
try now
