### ISSUE TITLE
Issue in step2

### ISSUE THREAD

**Issue by Parisa-Bagherzadeh** [guochengqian/Magic123#15]
I run this command : 
bash scripts/texural_inversion/textural_inversion.sh runwayml/stable-diffusion-v1-5 data/demo/ironman/rgba.png out/textual_inversion/ironman _ironman_ ironman --max_train_steps 3000

but got this error : 
textual_inversion.py: error: unrecognized arguments: 3000

what's the problem?!

**Comment by Myungkyu-Koo** [comment]
Try running it again with '$GPU_IDX' before 'runwayml/stable-diffusion-v1-5'.
