### ISSUE TITLE
[issue in step 1] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### ISSUE THREAD

**Issue by akaihaoshuai** [guochengqian/Magic123#18]
[23/08/10 19:40:31 nerf.utils]: ==> [2023-08-10_19-40-31] Start Training out/magic123-default-coarse/realfusion15/magic123_metal_dragon_statue_default_coarse Epoch 1/50, lr=0.010000 ...
> /data1/akai/coser/image_generate/Magic123/nerf/renderer.py(1493)update_extra_state()
-> xx, yy, zz = custom_meshgrid(xs, ys, zs)
(Pdb) c
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [213,0,0], thread: [32,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [213,0,0], thread: [33,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
...
...
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [298,0,0], thread: [62,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [298,0,0], thread: [63,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "main.py", line 594, in <module>
    if opt.learned_embeds_path is not None and os.path.exists(opt.learned_embeds_path):  # add textual inversion tokens to model
  File "/data1/Magic123/nerf/utils.py", line 1049, in train
    self.train_one_epoch(train_loader, max_epochs)
  File "/data1/Magic123/nerf/utils.py", line 1263, in train_one_epoch
    self.model.update_extra_state()
  File "/home/groot/apps/miniconda/envs/e3/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data1/Magic123/nerf/renderer.py", line 1493, in update_extra_state
    xx, yy, zz = custom_meshgrid(xs, ys, zs)
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

please tell me how to fix it，thank you.

**Comment by guochengqian** [comment]
What is your command

**Comment by akaihaoshuai** [comment]
> What is your command

command:  bash scripts/magic123/run_both_priors.sh 0 default dmtet data/realfusion15/metal_dragon_statue rgba.png 1 1


device: 4090 24G

**Comment by guochengqian** [comment]
Have you set export CUDA_VISIBLE_DEVICES to another value bigger than 0 before. Since you machine could not find gpu 0
