### ISSUE TITLE
run_both_priors.sh: RuntimeError: instance mode - pos much have shape [>0, >0, 4]

### ISSUE THREAD

**Issue by lzqsd** [guochengqian/Magic123#19]
Hi,

Thanks for the great work!

I am trying to run your method through run_both_prior.sh, through the example command you provided:
bash scripts/magic123/run_both_priors.sh 0 default dmtet data/realfusion15/metal_dragon_statue rgba.png 1 1 

However, I met an issue soon after training, which I will attached below. 

I looked into the issue a little bit and found that it is because in renderer.py, when we call run_dmtet function, the self.dmtet.get_verts_face() function will give us verts with shape [1, 0, 4]

It is a bit surprised that dmtet is called so early as it seems to be used for fine-tuning only. Would you please let me know what may cause this issue? Thanks a lot and looking forward to hearing from you!

[23/08/15 00:06:42 nerf.utils]: ==> [2023-08-15_00-06-42] Start Training out/magic123-default-dmtet/realfusion15/magic123_metal_dragon_statue_default_dmtet Epoch 1/50, lr=0.010000 ...
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\zhl\Documents\Code\Magic123\main.py:622 in <module>                                     │
│                                                                                                  │
│   619 │   │   │   │   opt, device=device, type='test', H=opt.H, W=opt.W, size=opt.dataset_size   │
│   620 │   │   │   max_epoch = np.ceil(opt.iters / len(train_loader)).astype(np.int32)            │
│   621 │   │   │                                                                                  │
│ ❱ 622 │   │   │   trainer.train(train_loader, valid_loader, test_loader, max_epoch)              │
│   623 │   │   │                                                                                  │
│   624 │   │   │   trainer.test(test_loader)                                                      │
│   625 │   │   │   trainer.test(test_loader, shading='normal') # save normal                      │
│                                                                                                  │
│ C:\Users\zhl\Documents\Code\Magic123\nerf\utils.py:1049 in train                                 │
│                                                                                                  │
│   1046 │   │   for epoch in range(self.epoch + 1, max_epochs + 1):                               │
│   1047 │   │   │   self.epoch = epoch                                                            │
│   1048 │   │   │                                                                                 │
│ ❱ 1049 │   │   │   self.train_one_epoch(train_loader, max_epochs)                                │
│   1050 │   │   │                                                                                 │
│   1051 │   │   │   if self.workspace is not None and self.local_rank == 0:                       │
│   1052 │   │   │   │   self.save_checkpoint(full=True, best=False)                               │
│                                                                                                  │
│ C:\Users\zhl\Documents\Code\Magic123\nerf\utils.py:1278 in train_one_epoch                       │
│                                                                                                  │
│   1275 │   │   │   self.optimizer.zero_grad()                                                    │
│   1276 │   │   │                                                                                 │
│   1277 │   │   │   with torch.cuda.amp.autocast(enabled=self.fp16):                              │
│ ❱ 1278 │   │   │   │   loss, losses_dict, outputs = self.train_step(data)                        │
│   1279 │   │   │                                                                                 │
│   1280 │   │   │   # hooked grad clipping for RGB space                                          │
│   1281 │   │   │   if self.opt.grad_clip_rgb >= 0:                                               │
│                                                                                                  │
│ C:\Users\zhl\Documents\Code\Magic123\nerf\utils.py:645 in train_step                             │
│                                                                                                  │
│    642 │   │   │   else:                                                                         │
│    643 │   │   │   │   bg_color = torch.rand(3).to(self.device) # single color random bg         │
│    644 │   │                                                                                     │
│ ❱  645 │   │   outputs = self.model.render(rays_o, rays_d, mvp, H, W, staged=False, perturb=Tru  │
│    646 │   │   pred_depth = outputs['depth'].reshape(B, 1, H, W)                                 │
│    647 │   │   if self.opt.normalize_depth:                                                      │
│    648 │   │   │   pred_depth = nonzero_normalize_depth(pred_depth)                              │
│                                                                                                  │
│ C:\Users\zhl\Documents\Code\Magic123\nerf\renderer.py:1522 in render                             │
│                                                                                                  │
│   1519 │   │   device = rays_o.device                                                            │
│   1520 │   │                                                                                     │
│   1521 │   │   if self.dmtet:                                                                    │
│ ❱ 1522 │   │   │   results = self.run_dmtet(rays_o, rays_d, mvp, h, w, **kwargs)                 │
│   1523 │   │   elif self.cuda_ray:                                                               │
│   1524 │   │   │   results = self.run_cuda(rays_o, rays_d, **kwargs)                             │
│   1525 │   │   elif self.taichi_ray:                                                             │
│                                                                                                  │
│ C:\Users\zhl\Documents\Code\Magic123\nerf\renderer.py:1265 in run_dmtet                          │
│                                                                                                  │
│   1262 │   │   # rasterization                                                                   │
│   1263 │   │   verts_clip = torch.bmm(F.pad(verts, pad=(0, 1), mode='constant', value=1.0).unsq  │
│   1264 │   │   │   │   │   │   │      mvp.permute(0,2,1)).float()  # [B, N, 4]                   │
│ ❱ 1265 │   │   rast, rast_db = dr.rasterize(self.glctx, verts_clip, faces, (h, w))               │
│   1266 │   │                                                                                     │
│   1267 │   │   alpha, _ = dr.interpolate(torch.ones_like(verts[:, :1]).unsqueeze(0), rast, face  │
│   1268 │   │   xyzs, _ = dr.interpolate(verts.unsqueeze(0), rast, faces) # [B, H, W, 3]          │
│                                                                                                  │
│ C:\Users\zhl\Anaconda3\lib\site-packages\nvdiffrast\torch\ops.py:310 in rasterize                │
│                                                                                                  │
│   307 │   │   return RuntimeError("Cannot call rasterize() during depth peeling operation, use   │
│   308 │                                                                                          │
│   309 │   # Instantiate the function.                                                            │
│ ❱ 310 │   return _rasterize_func.apply(glctx, pos, tri, resolution, ranges, grad_db, -1)         │
│   311                                                                                            │
│   312 #----------------------------------------------------------------------------              │
│   313 # Depth peeler context manager for rasterizing multiple depth layers.                      │
│                                                                                                  │
│ C:\Users\zhl\Anaconda3\lib\site-packages\torch\autograd\function.py:506 in apply                 │
│                                                                                                  │
│   503 │   │   if not torch._C._are_functorch_transforms_active():                                │
│   504 │   │   │   # See NOTE: [functorch vjp and autograd interaction]                           │
│   505 │   │   │   args = _functorch.utils.unwrap_dead_wrappers(args)                             │
│ ❱ 506 │   │   │   return super().apply(*args, **kwargs)  # type: ignore[misc]                    │
│   507 │   │                                                                                      │
│   508 │   │   if cls.setup_context == _SingleLevelFunction.setup_context:                        │
│   509 │   │   │   raise RuntimeError(                                                            │
│                                                                                                  │
│ C:\Users\zhl\Anaconda3\lib\site-packages\nvdiffrast\torch\ops.py:248 in forward                  │
│                                                                                                  │
│   245 │   │   if isinstance(raster_ctx, RasterizeGLContext):                                     │
│   246 │   │   │   out, out_db = _get_plugin(gl=True).rasterize_fwd_gl(raster_ctx.cpp_wrapper,    │
│   247 │   │   else:                                                                              │
│ ❱ 248 │   │   │   out, out_db = _get_plugin().rasterize_fwd_cuda(raster_ctx.cpp_wrapper, pos,    │
│   249 │   │   ctx.save_for_backward(pos, tri, out)                                               │
│   250 │   │   ctx.saved_grad_db = grad_db                                                        │
│   251 │   │   return out, out_db                                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: instance mode - pos must have shape [>0, >0, 4]

**Comment by guochengqian** [comment]
hi @lzqsd 

sorry, I updated the scripts and forgot to revise readme command. Here is the new command:

```
bash scripts/magic123/run_both_priors.sh 0 nerf dmtet data/realfusion15/metal_dragon_statue 1 1 
```
Please try and let me know if you have any question

**Comment by lzqsd** [comment]
Thanks for the quick response! It makes sense.
