### ISSUE TITLE
😘😍😀「𝕙𝕒𝕓𝕚𝕓𝕚 𝕗𝕚𝕣𝕤𝕥 𝕤𝕠𝕗𝕒 𝕡𝕠𝕤𝕥」𝕎𝕒𝕚𝕥𝕚𝕟𝕘 𝕗𝕠𝕣 𝕪𝕠𝕦𝕣 𝕖𝕩𝕔𝕖𝕝𝕝𝕖𝕟𝕥 𝕨𝕠𝕣𝕜 𝕒𝕤 𝕞𝕪 𝕗𝕚𝕣𝕤𝕥 𝕡𝕣𝕠𝕛𝕖𝕔𝕥 𝕒𝕗𝕥𝕖𝕣 𝕒 𝕪𝕖𝕒𝕣. 👨‍💻🧕🏻🧑🏻‍⚕️

### ISSUE THREAD

**Issue by yuchenlichuck** [guochengqian/Magic123#2]
「͟h͟a͟b͟i͟b͟i͟ ͟f͟i͟r͟s͟t͟ ͟s͟o͟f͟a͟ ͟p͟o͟s͟t͟」͟W͟a͟i͟t͟i͟n͟g͟ ͟f͟o͟r͟ ͟y͟o͟u͟r͟ ͟e͟x͟c͟e͟l͟l͟e͟n͟t͟ ͟w͟o͟r͟k͟ ͟a͟s͟ ͟m͟y͟ ͟f͟i͟r͟s͟t͟ ͟p͟r͟o͟j͟e͟c͟t͟ ͟a͟f͟t͟e͟r͟ ͟a͟ ͟y͟e͟a͟r͟.͟

From Dubai

**Comment by guochengqian** [comment]
thanks @yuchenlichuck hope best for your new journey as well.
