### ISSUE TITLE
Installation Errors

### ISSUE THREAD

**Issue by anandvarrier** [guochengqian/Magic123#25]
Hey @guochengqian,
I was waiting for your code to release for so long and finally it is released. The demos look really impressive.

1) I am trying to implement your code on my system. I have an Intel(R) Xeon(R) CPU E5-2680 0, NVIDIA GeForce GTX 1660 Ti GPU. 
On PyCharm venv, when I tried installing requirements.txt file, it started giving me errors saying 'ModuleNotFoundError: No module named 'torch'. I then manually installed all the packages. When I displayed 'pip list', I can see torch 1.13.1+cu117, torch-vision 0.1.6.dev0, torchaudio 0.13.1, torchvision 0.14.1. 

Then I proceeded ahead to download the 2 pre-trained models manually and kept them in their respective folders. 

I then created my own folder under data/demos and uploaded a .png file of 1002 x 1002 pixels.

I ran the preprocess_image.py file by giving an absolute path. Here, it again gave me an error saying the following:

 UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\
src\ATen\native\TensorShape.cpp:3191.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Model loaded, number of parameters = 345M
[INFO] loading image /E:/User/Magic123_/Magic123/data/demo/imagefolder/image.png...
[ WARN:0@29.339] global loadsave.cpp:248 cv::findDecoder imread_('/E:/User/Magic123_/Magic123/data/demo/imagefolder/image.png'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "preprocess_image.py", line 277, in <module>
    process_single_image(path, depth_estimator,
  File "preprocess_image.py", line 209, in process_single_image
    if image.shape[-1] == 4:
AttributeError: 'NoneType' object has no attribute 'shape'

I thought all requirements were not fulfilled, so I again ran 'pip install -r requirements.txt'. It gave me the following error:

Collecting git+https://github.com/NVlabs/nvdiffrast/ (from -r requirements.txt (line 35))
  Cloning https://github.com/NVlabs/nvdiffrast/ to c:\users\umesh\appdata\local\temp\pip-req-build-46u0wfek
  Running command git clone --filter=blob:none --quiet https://github.com/NVlabs/nvdiffrast/ 'C:\Users\user\AppData\Local\Temp\pip-req-build-46u0wfek'
  Resolved https://github.com/NVlabs/nvdiffrast/ to commit c5caf7bdb8a2448acc491a9faa47753972edd380
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting git+https://github.com/openai/CLIP.git (from -r requirements.txt (line 45))
  Cloning https://github.com/openai/CLIP.git to c:\users\umesh\appdata\local\temp\pip-req-build-278rxy5f
  Running command git clone --filter=blob:none --quiet https://github.com/openai/CLIP.git 'C:\Users\user\AppData\Local\Temp\pip-req-build-278rxy5f'
  Resolved https://github.com/openai/CLIP.git to commit a1d071733d7111c9c014f024669f959182114e33
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting git+https://github.com/ashawkey/cubvh (from -r requirements.txt (line 55))
  Cloning https://github.com/ashawkey/cubvh to c:\users\umesh\appdata\local\temp\pip-req-build-_xosaue2
  Running command git clone --filter=blob:none --quiet https://github.com/ashawkey/cubvh 'C:\Users\user\AppData\Local\Temp\pip-req-build-_xosaue2'
  Resolved https://github.com/ashawkey/cubvh to commit d3e923c90e56974d39f57c2e2b9bf372d2e45870
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "e:\user\magic123_\m123env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "e:\user\magic123_\m123env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "e:\user\magic123_\m123env\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-y9hro2_3\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-y9hro2_3\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-y9hro2_3\overlay\Lib\site-packages\setuptools\build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-y9hro2_3\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 3, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

I am unsure what the problem is exactly because, I even tried creating a new virtual env and redoing the same steps but in no vain. 
Could you guide what can be exactly done to resolve this issue?

Thank you!

**Comment by guochengqian** [comment]
Sorry, I do not help with installations.
