### ISSUE TITLE
Hyperparameter of  the each mesh

### ISSUE THREAD

**Issue by Subin-Kim46** [guochengqian/Magic123#29]
Hi,

Thank you for your great research.
Using Magic 123, I drew mash as a picture of a person. However, the result of the mesh wasn't good..
The distinction between the ends of the pants and the legs is not clear. And, back of the mesh was strange 

So, I want to know the hyperparameter's of  the Lisa's mesh and Taylor swift's mesh.
how to make a clear mesh like Lisa and Taylor swift?

**Comment by guochengqian** [comment]
No parameter tuning at all. Use the default for all examples.

**Comment by guochengqian** [comment]
For your research, you can add SMPL as a prior to enhance results.
