### ISSUE TITLE
I'm currently experiencing a token-related issue

### ISSUE THREAD

**Issue by kimsh0622** [guochengqian/Magic123#30]
(venv_magic123) (base) root@36d231460096:~/Magic123# bash scripts/textual_inversion/textual_inversion.sh runwayml/stable-diffusion-v1-5 data/nerf4/chair _chair_ chair --max_train_steps=3000
===> Anaconda env loaded
36d231460096
number of gpus: 4
09/08/2023 05:00:40 - INFO - __main__ - Namespace(adam_beta1=0.9, adam_beta2=0.999, adam_epsilon=1e-08, adam_weight_decay=0.01, allow_tf32=False, center_crop=False, checkpointing_steps=500, checkpoints_total_limit=None, dataloader_num_workers=0, enable_xformers_memory_efficient_attention=False, gradient_accumulation_steps=1, gradient_checkpointing=False, hub_model_id=None, hub_token=None, initializer_token='', learnable_property='object', learning_rate=0.0001, local_rank=-1, logging_dir='logs', lr_scheduler='constant', lr_warmup_steps=0, max_train_steps=3000, mixed_precision='no', num_train_epochs=100, num_validation_images=4, only_save_embeds=False, output_dir='chair', placeholder_token='--max_train_steps=3000', pretrained_model_name_or_path='data/nerf4/chair', push_to_hub=False, repeats=100, report_to='tensorboard', resolution=512, resume_from_checkpoint=None, revision=None, save_steps=500, scale_lr=False, seed=None, tokenizer_name=None, train_batch_size=16, train_data_dir='_chair_', use_augmentations=True, validation_epochs=None, validation_prompt=None, validation_steps=100)
09/08/2023 05:00:40 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cpu

Mixed precision type: no

Traceback (most recent call last):
  File "textual-inversion/textual_inversion.py", line 927, in <module>
    main()
  File "textual-inversion/textual_inversion.py", line 628, in main
    tokenizer = CLIPTokenizer.from_pretrained(args.pretrained_model_name_or_path, subfolder="tokenizer")
  File "/root/Magic123/venv_magic123/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1838, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'data/nerf4/chair'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'data/nerf4/chair' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.

I'm currently experiencing a token-related issue as shown above. Could you please assist me in resolving this? Thank you

**Comment by kimsh0622** [comment]
Run

(venv_magic123) (base) root@36d231460096:~/Magic123# bash scripts/magic123/run_both_priors.sh 0 nerf dmtet data/realfusion15/metal_dragon_statue 1 1

Traceback (most recent call last):
  File "main.py", line 622, in <module>
    trainer.train(train_loader, valid_loader, test_loader, max_epoch)
  File "/root/Magic123/nerf/utils.py", line 1049, in train
    self.train_one_epoch(train_loader, max_epochs)
  File "/root/Magic123/nerf/utils.py", line 1278, in train_one_epoch
    loss, losses_dict, outputs = self.train_step(data)
  File "/root/Magic123/nerf/utils.py", line 645, in train_step
    outputs = self.model.render(rays_o, rays_d, mvp, H, W, staged=False, perturb=True, bg_color=bg_color, ambient_ratio=ambient_ratio, shading=shading, binarize=binarize)
  File "/root/Magic123/nerf/renderer.py", line 1521, in render
    results = self.run_dmtet(rays_o, rays_d, mvp, h, w, **kwargs)
  File "/root/Magic123/nerf/renderer.py", line 1264, in run_dmtet
    rast, rast_db = dr.rasterize(self.glctx, verts_clip, faces, (h, w))
  File "/root/Magic123/venv_magic123/lib/python3.8/site-packages/nvdiffrast/torch/ops.py", line 310, in rasterize
    return _rasterize_func.apply(glctx, pos, tri, resolution, ranges, grad_db, -1)
  File "/root/Magic123/venv_magic123/lib/python3.8/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/root/Magic123/venv_magic123/lib/python3.8/site-packages/nvdiffrast/torch/ops.py", line 248, in forward
    out, out_db = _get_plugin().rasterize_fwd_cuda(raster_ctx.cpp_wrapper, pos, tri, resolution, ranges, peeling_idx)
RuntimeError: instance mode - pos must have shape [>0, >0, 4]

**Comment by kimsh0622** [comment]
I want to implement data parallel processing due to memory limitations. Are there any methods available to use multiple GPUs?

**Comment by guochengqian** [comment]
@kimsh0622  you can use threestudio's reimplementation. They supports multigpu. https://github.com/threestudio-project/threestudio#magic123-
