### ISSUE TITLE
Getting the foreground mask from each pixel

### ISSUE THREAD

**Issue by Gynjn** [guochengqian/Magic123#33]
First, Thanks for your great work!

In paper page 4, "the M() is the foreground mask acquired by integrating the volume density along the ray of each pixel.", How could calulate the density in pixel? 

For example, the naive NeRF gets density (sigma) from 3d coord query. Then just add them in all samples in ray and normalize?

Thanks.

**Comment by guochengqian** [comment]
https://github.com/guochengqian/Magic123/blob/7f051875e48988dc624b2bd8425aea370c093588/nerf/renderer.py#L1073
