### ISSUE TITLE
 Unexpected key(s) in state_dict

### ISSUE THREAD

**Issue by spider-fly** [guochengqian/Magic123#34]
(pytorch_wsh) D:\迅雷下载\Magic123-main>python preprocess_image.py --path data/demo/a-full-body-ironman/image.png
Traceback (most recent call last):
  File "D:\迅雷下载\Magic123-main\preprocess_image.py", line 266, in <module>
    depth_estimator = DepthEstimator()
  File "D:\迅雷下载\Magic123-main\preprocess_image.py", line 158, in __init__
    model, transform, net_w, net_h = load_model(f"cuda:{self.config.device}", self.config.model_weights, self.config.model_type,
  File "D:\迅雷下载\Magic123-main\midas\model_loader.py", line 50, in load_model
    model = DPTDepthModel(
  File "D:\迅雷下载\Magic123-main\midas\dpt_depth.py", line 163, in __init__
    self.load(path)
  File "D:\迅雷下载\Magic123-main\midas\base_model.py", line 16, in load
    self.load_state_dict(parameters)
  File "E:\anaconda\envs\pytorch_wsh\lib\site-packages\torch\nn\modules\module.py", line 1223, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DPTDepthModel:
        Unexpected key(s) in state_dict: "pretrained.model.blocks.0.attn.relative_position_index", "pretrained.model.blocks.1.attn.relative_position_index", "pretrained.mo
del.blocks.2.attn.relative_position_index", "pretrained.model.blocks.3.attn.relative_position_index", "pretrained.model.blocks.4.attn.relative_position_index", "pretrained
.model.blocks.5.attn.relative_position_index", "pretrained.model.blocks.6.attn.relative_position_index", "pretrained.model.blocks.7.attn.relative_position_index", "pretrai
ned.model.blocks.8.attn.relative_position_index", "pretrained.model.blocks.9.attn.relative_position_index", "pretrained.model.blocks.10.attn.relative_position_index", "pre
trained.model.blocks.11.attn.relative_position_index", "pretrained.model.blocks.12.attn.relative_position_index", "pretrained.model.blocks.13.attn.relative_position_index"
, "pretrained.model.blocks.14.attn.relative_position_index", "pretrained.model.blocks.15.attn.relative_position_index", "pretrained.model.blocks.16.attn.relative_position_
index", "pretrained.model.blocks.17.attn.relative_position_index", "pretrained.model.blocks.18.attn.relative_position_index", "pretrained.model.blocks.19.attn.relative_pos
ition_index", "pretrained.model.blocks.20.attn.relative_position_index", "pretrained.model.blocks.21.attn.relative_position_index", "pretrained.model.blocks.22.attn.relative_position_index", "pretrained.model.blocks.23.attn.relative_position_index".

**Comment by hanbaobao950123** [comment]
I have the same problem, and how can I solve it？
