### ISSUE TITLE
I cannot load DDPMScheduler in runwayml/stable-diffusion-v1-5

### ISSUE THREAD

**Issue by TimenoLong** [guochengqian/Magic123#37]
OSError: Error no file named scheduler_config.json found in directory runwayml/stable-diffusion-v1-5.

**Comment by TimenoLong** [comment]
The following pieces of code cannot load the corresponding models：
    # Load scheduler and models
    noise_scheduler = DDPMScheduler.from_pretrained(args.pretrained_model_name_or_path, subfolder="scheduler")
    text_encoder = CLIPTextModel.from_pretrained(
        args.pretrained_model_name_or_path, subfolder="text_encoder", revision=args.revision
    )
    vae = AutoencoderKL.from_pretrained(args.pretrained_model_name_or_path, subfolder="vae", revision=args.revision)
    unet = UNet2DConditionModel.from_pretrained(
        args.pretrained_model_name_or_path, subfolder="unet", revision=args.revision
    )

**Comment by guochengqian** [comment]
it might be due to the update of the diffuser library. Could you check the specific version we use here: https://github.com/guochengqian/Magic123/blob/main/requirements-torch201-cuda117.txt

**Comment by TimenoLong** [comment]
Okey, thank you very much!  I've fixed the problem, it's due to a network issue.
