### ISSUE TITLE
Issue with Figure 5 in Results

### ISSUE THREAD

**Issue by sangminkim-99** [guochengqian/Magic123#4]
Hi @guochengqian,

I want to express my gratitude for sharing this outstanding work. The results are truly impressive!

However, I noticed a potential issue with Figure 5. It seems that the results of RealFusion are swapped between the Reference and Novel at the bottom of the figure. This discrepancy initially caused confusion for me.

I kindly request you to review and fix this aspect of Figure 5 to ensure the accurate representation of the results.

Thank you.

**Comment by guochengqian** [comment]
Hi @sangminkim-99  thanks for letting me know. Fixing it now.

**Comment by guochengqian** [comment]
Done. Changes will appear in the updated arxiv.
