### ISSUE TITLE
Why include CLS token in the text embedding

### ISSUE THREAD

**Issue by Trainingzy** [guochengqian/Magic123#40]
Thanks for your great work!

I notice that you include both hidden state and CLS token in stable diffusion text embeddings [here](https://github.com/guochengqian/Magic123/blob/7f051875e48988dc624b2bd8425aea370c093588/nerf/utils.py#L351C80-L351C80). However, in stable diffusion 1.5, the text embedding does not include the CLS token. 

I also checked stable dreamfusion. It also not use CLS token [here](https://github.com/ashawkey/stable-dreamfusion/blob/5550b91862a3af7842bb04875b7f1211e5095a63/nerf/utils.py#L359). 

May I know why you include CLS token here?

**Comment by Wakeelfahmed** [comment]
are u able to use the pretrained model? I am unable to set up the model/environment. 
Would u please help?

**Comment by guochengqian** [comment]
yes, I will provide pretrained model once I go back to Snap (around Dec 1st). Now I do not have access to their platforms.

**Comment by guochengqian** [comment]
we use that for textual inversion.
