### ISSUE TITLE
Without a export mesh in "mesh" folder.

### ISSUE THREAD

**Issue by gaoxiangjun** [guochengqian/Magic123#45]
It seems that self.model.export_mesh() isn't be executed.
Please check the results

**Comment by yuhuangyue** [comment]
it is because wrong version of pymeshlab
you should 
`pip install pymeshlab==2022.2.post4`

**Comment by gaoxiangjun** [comment]
Thanks a lot for your reply! I would try that.

**Comment by guochengqian** [comment]
@yuhuangyue  Thank you for your information!
