### ISSUE TITLE
Having issues installing cubvh on windows machine

### ISSUE THREAD

**Issue by DiamondGlassDrill** [guochengqian/Magic123#7]
Currently trying to install magic123, I build a .bat installer to get everything under control, as install.sh in my mamba environment doesn't work (it is a "windows" thing). 
So currently getting the error:
      ...\mambaforge\envs\magic123\lib\site-packages\torch\include\pybind11/eigen.h(35): fatal error C1083: File cannot be opened: "Eigen/Core": No such file or directory
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "...\mambaforge\envs\magic123\lib\site-packages\torch\utils\cpp_extension.py", line 1893, in _run_ninja_build
          subprocess.run(
        File "...\mambaforge\envs\magic123\lib\subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,

Going down the rabbid hole I am currently in the pybind11/eigen.h and there it tries to load Eigen but no folder is in the pybind11
From eigen.h (extracted)
```
/*
    pybind11/eigen.h: Transparent conversion for dense and sparse Eigen matrices

    Copyright (c) 2016 Wenzel Jakob <wenzel.jakob@epfl.ch>

    All rights reserved. Use of this source code is governed by a
    BSD-style license that can be found in the LICENSE file.
*/

#pragma once

/* HINT: To suppress warnings originating from the Eigen headers, use -isystem.
   See also:
       https://stackoverflow.com/questions/2579576/i-dir-vs-isystem-dir
       https://stackoverflow.com/questions/1741816/isystem-for-ms-visual-studio-c-compiler
*/

#include "numpy.h"

// The C4127 suppression was introduced for Eigen 3.4.0. In theory we could
// make it version specific, or even remove it later, but considering that
// 1. C4127 is generally far more distracting than useful for modern template code, and
// 2. we definitely want to ignore any MSVC warnings originating from Eigen code,
//    it is probably best to keep this around indefinitely.
#if defined(_MSC_VER)
#    pragma warning(push)
#    pragma warning(disable : 4127) // C4127: conditional expression is constant
#    pragma warning(disable : 5054) // https://github.com/pybind/pybind11/pull/3741
//       C5054: operator '&': deprecated between enumerations of different types
#elif defined(__MINGW32__)
#    pragma GCC diagnostic push
#    pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
#endif

#include <Eigen/Core>
#include <Eigen/SparseCore>
```

...

Maybe someone has the same issue and could help?

I have pytorch 2.0.1 installed for python 3.10 and CUDA 11.8 with cuDNN 8.0

**Things done so far:**

1. pip install eigen (0.0.1 from 2022) didn't help (uninstalled)
2. mamba install eigenpy (3.1.0 from July 2023) (gives latest Eigen 3.4.0 (2021)) but didn't help

**Comment by DiamondGlassDrill** [comment]
Solved one issue, as I added within the setup.py of cubvh the missing link to the right Eigen folder.

```
    # Get the current path of the active conda/mamba environment
    current_env_path = os.environ.get('CONDA_PREFIX', None)
    if current_env_path:
        eigen_path = os.path.join(current_env_path, 'Library', 'include', 'eigen3')
        print(eigen_path)
    else:
        eigen_path = None
    if eigen_path:
        try_paths.append(eigen_path)
```

**A bit dirty but it works for now.**


**Another issue appeared.**


```

      ...\mambaforge\envs\magic123\Library\include\eigen3\Eigen\src/Core/Ref.h(63): note: See declaration of  "Eigen::RefBase<Eigen::Ref<const Eigen::Matrix<unsigned int,-1,3,1,-1,3>,0,Eigen::OuterStride<-1>>>::StrideType"

      ...\mambaforge\envs\magic123\Library\include\eigen3\Eigen\src/Core/Ref.h(329): note: See declaration of "Eigen::RefBase<Eigen::Ref<const Eigen::Matrix<unsigned int,-1,3,1,-1,3>,0,Eigen::OuterStride<-1>>>"

      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "...\mambaforge\envs\magic123\lib\site-packages\torch\utils\cpp_extension.py", line 1893, in _run_ninja_build
          subprocess.run(
        File "...\mambaforge\envs\magic123\lib\subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.


```
I know it is not hinting to the error but currently have lost already 2h; will debug it later, but maybe someone else has the same issue and will fix it meanwhile :)

**Comment by guochengqian** [comment]
For installation issues, you can refer to the stable-dreamfusion repo. Our code is highly built upon them.

**Comment by guochengqian** [comment]
https://github.com/guochengqian/Magic123/blob/main/requirements-torch201-cuda117.txt

**Comment by ghpkishore** [comment]
@DiamondGlassDrill Can you share your bat file? I am also trying to isntall the repo in windows machine and am currently struggling. Any help is appreciated

**Comment by Mankeylol** [comment]
Would also appreciate some help setting it up on a windows machine
